### ISSUE TITLE
Input search in the Vue component

### ISSUE THREAD

**Issue by williampaulo** [plantain-00/select2-component#21]
The Vue component has the input hidden all the time even past the minCountForSearch pre-metric with any number

**Comment by plantain-00** [comment]
Can you explain more about this issue? I cannot reproduce it.

**Comment by williampaulo** [comment]
Hi, I searched for some cdn with the script to upload an example in jsfiddle but I did not find it.
my code

```
<template>
  <div class="container">
    <select2 :data="data1"
          :value="value1"
          @update="update1($event)">
    </select2>
  </div>
</template>

<script>

import 'select2-vue-component'
import 'bootstrap/dist/css/bootstrap.css'
import 'select2-component/dist/select2.css'

export default {
  name: 'app',
  components: {
    // Select2
  },
  data() {
    return {
      data1: [
        { value: 'CA', label: 'California' },
        { value: 'NV', label: 'Nevada' },
        { value: 'OR', label: 'Oregon' },
        { value: 'WA', label: 'Washington' }
      ],
      value1: 'WA'
    }
  },
  methods: {
    update1: function () {
      console.log('opa')
    }
  }
}
</script>
```

Result

![captura de tela de 2017-12-18 09-25-39](https://user-images.githubusercontent.com/5365376/34106074-9376d53c-e3d5-11e7-9018-6b1f86c6560a.png)

**Comment by plantain-00** [comment]
Your example seem correct.
Do you want the search box is always visible? the document(https://github.com/plantain-00/select2-component#properties-and-events-of-the-component) says `hide search box if options.length < minCountForSearch`, so if `minCountForSearch = 0`, then `options.length < minCountForSearch` is always false, then the search box is always visible. otherwise`Infinity` then always hidden.

**Comment by williampaulo** [comment]
Okay, thanks for your help.
